from django.db import migrations, models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
class Migration(migrations.Migration):
 initial=True
 dependencies=[('auth','0012_alter_user_first_name_max_length')]
 operations=[
  migrations.CreateModel(name='User',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('password',models.CharField(max_length=128,verbose_name='password')),('last_login',models.DateTimeField(blank=True,null=True,verbose_name='last login')),('is_superuser',models.BooleanField(default=False,help_text='Designates that this user has all permissions without explicitly assigning them.',verbose_name='superuser status')),('username',models.CharField(max_length=150,unique=True)),('first_name',models.CharField(blank=True,max_length=150)),('last_name',models.CharField(blank=True,max_length=150)),('email',models.EmailField(blank=True,max_length=254)),('is_staff',models.BooleanField(default=False)),('is_active',models.BooleanField(default=True)),('date_joined',models.DateTimeField(auto_now_add=True)),('role',models.CharField(max_length=30,default='CITIZEN')),('phone',models.CharField(blank=True,max_length=30)),('groups',models.ManyToManyField(blank=True,related_name='core_user_set',related_query_name='core_user',to='auth.group')),('user_permissions',models.ManyToManyField(blank=True,related_name='core_user_set',related_query_name='core_user',to='auth.permission'))],options={'abstract':False}),
  migrations.CreateModel(name='Department',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('code',models.CharField(max_length=30,unique=True)),('categories',models.JSONField(blank=True,default=list)),('head',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='headed_departments',to='core.user'))]),
  migrations.CreateModel(name='CitizenProfile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('address',models.CharField(blank=True,max_length=255)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='citizen_profile',to='core.user'))]),
  migrations.CreateModel(name='WorkerProfile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('employee_id',models.CharField(max_length=50,unique=True)),('skills',models.JSONField(blank=True,default=list)),('current_location',django.contrib.gis.db.models.fields.PointField(blank=True,null=True,srid=4326)),('department',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='workers',to='core.department')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='worker_profile',to='core.user'))]),
  migrations.CreateModel(name='Complaint',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(db_index=True,max_length=30,unique=True)),('title',models.CharField(max_length=200)),('description',models.TextField()),('category',models.CharField(max_length=40,default='OTHER')),('status',models.CharField(max_length=30,default='REPORTED')),('priority',models.CharField(max_length=20,default='MEDIUM')),('priority_score',models.PositiveSmallIntegerField(default=0)),('priority_reasons',models.JSONField(blank=True,default=list)),('location',django.contrib.gis.db.models.fields.PointField(srid=4326)),('address',models.CharField(blank=True,max_length=255)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('resolved_at',models.DateTimeField(blank=True,null=True)),('citizen',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='complaints',to='core.user')),('department',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='complaints',to='core.department'))],options={'indexes':[models.Index(fields=['status','priority'],name='core_complaint_status_priority_idx'),models.Index(fields=['category','created_at'],name='core_complaint_category_created_idx')]}),
  migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS postgis;"),
 ]

